# Generated by Django 4.0.3 on 2022-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='feature_image',
        ),
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='project_images'),
        ),
    ]
